COMPUTE_IP ?= "192.168.7.4"
COMPUTE_HOST ?= "compute" 
CONTROLLER_IP ?= "192.168.7.2"
CONTROLLER_HOST ?= "controller"
MY_IP ?= "${COMPUTE_IP}"
MY_HOST ?= "${COMPUTE_HOST}"
DB_DATADIR ?= "/etc/postgresql"
