#!/bin/sh

### BEGIN INIT INFO
# Provides:
# Required-Start: $remote_fs $network $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Cinder Test Config
# Description: OpenStack Cinder Test Config
### END INIT INFO


start()
{
    sleep 2
    source /etc/nova/openrc
    /etc/cinder/add-cinder-volume-types.sh > /dev/null 2>&1
}

case "$1" in
    start)
        start
        ;;
    stop|force-reload|restart|reload|status)
        echo "WARNING: command $1 is not supported"
        ;;
    *)
        echo "Usage: $0 {start|stop|force-reload|restart|reload|status}"
        exit 1
        ;;
esac

exit 0
