dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2080a-simu.dtb fsl-ls2080a-qds.dtb fsl-ls2080a-rdb.dtb \
				fsl-ls1043a-rdb.dtb fsl-ls1043a-qds.dtb fsl-ls1043a-uefi-rdb.dtb \
				fsl-ls1088a-rdb.dtb fsl-ls2088a-emu.dtb fsl-ls2088a-simu.dtb \
				fsl-ls2088a-qds.dtb fsl-ls2088a-rdb.dtb fsl-ls1088a-qds.dtb
 
always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
